<?php
$dischi = [
   [
      "poster" => "AbbeyRoadTheBeatles.jpg",
      "title" => "Abbey Road - Life is what happens to you while you're busy making other plans.",
      "author" => "The Beatles",
      "status" => "Recently played",
      "genre" => "Rock",
      "year" => "1969",
   ],
   [
      "poster" => "os-tincoas.jpg",
      "title" => "independentes do Brasil clube de registros",
      "author" => "Os Tincoãs",
      "status" => "Recently played",
      "genre" => "popular",
      "year" => "1973",
   ],
   [
      "poster" => "PinkFloyd-darkSideOfTheMoon.jpg",
      "title" => "Dark Side Of The Moon - An instance of political, philosophical and humanitarian empathy that desperately asked to come out.",
      "author" => "Pink Floyd",
      "status" => "Recently played",
      "genre" => "Rock",
      "year" => "1973",
   ],
   [
      "poster" => "bob-marley_gold.jpg",
      "title" => "Gold - You never know how strong you are until being strong is the only choice you have.",
      "author" => "Bob Marley",
      "status" => "Recently played",
      "genre" => "Reggae",
      "year" => "2005",
   ],
   [
      "poster" => "acdc-forThoseAboutRock.jpg",
      "title" => "For Those About Rock - The earth was quaking, My mind was aching and we were making it And you shoook me all night long.",
      "author" => "AC/DC",
      "status" => "Recently played",
      "genre" => "Rock",
      "year" => "1981",
   ],
   [
      "poster" => "MichealCleis-LaMezcla.jpg",
      "title" => "La Mezcla - People are strange when you're a stranger, faces look ugly when you're alore women seems wicked when you're unwanted.",
      "author" => "Micheal Cleis",
      "status" => "Recently played",
      "genre" => "House",
      "year" => "2009",
   ],
   [
      "poster" => "radar.jpeg",
      "title" => "",
      "author" => "Release Radar",
      "status" => "created for user",
      "genre" => "",
      "year" => "",
   ],
   [
      "poster" => "man_on_elephant.jpg",
      "title" => "",
      "author" => "Daily Mix 1",
      "status" => "created for user",
      "genre" => "",
      "year" => "",
   ],
   [
      "poster" => "ninaSimone_sink&soul.jpg",
      "title" => "This is the world you have made yourself, now you have to live in it.",
      "author" => "Nina Simone",
      "status" => "popolar artists",
      "genre" => "Jazz",
      "year" => "1965",
   ],
   [
      "poster" => "Fabrizio-De-Andre-La-Buona-Novellajpg.jpg",
      "title" => "Vuoi davvero lasciare ai tuoi occhi solo i sogni che non fanno svegliare?",
      "author" => "De Andrè",
      "status" => "popolar artists",
      "genre" => "Folk",
      "year" => "1978",
   ],
]
?>